import sys
import json
import urllib.request

def fetch(video_id):
    try:
        # Usamos una instancia pública de Piped/Invidious como proxy para la API de YouTube
        api_url = f"https://api.piped.inc/streams/{video_id}"
        req = urllib.request.Request(api_url, headers={'User-Agent': 'Mozilla/5.0'})
        data = json.loads(urllib.request.urlopen(req).read().decode('utf-8'))
        
        title = data.get('title', 'Unknown Title')
        subtitles = data.get('subtitles', [])
        
        if not subtitles:
            print(json.dumps({"error": "No subtitles found on proxy"}))
            return
            
        # Buscar subtítulo auto-generado o ES/EN
        sub_url = subtitles[0].get('url')
        for sub in subtitles:
            if sub.get('autoGenerated') and 'en' in sub.get('code', ''):
                sub_url = sub.get('url')
                break

        if not sub_url:
            print(json.dumps({"error": "Subtitle URL missing"}))
            return
            
        sub_xml = urllib.request.urlopen(sub_url).read().decode('utf-8')
        
        import xml.etree.ElementTree as ET
        root = ET.fromstring(sub_xml)
        text = " ".join([elem.text for elem in root.findall('.//p') if elem.text])
        if not text:
             # Fallback if standard VTT format
             text = sub_xml.replace('\n', ' ')

        print(json.dumps({
            "video_id": video_id,
            "title": title,
            "full_text": text
        }))
        
    except Exception as e:
        print(json.dumps({"error": str(e)}))

if len(sys.argv) > 1:
    import re
    url = sys.argv[1]
    match = re.search(r'(?:v=|/v/|youtu\.be/|/embed/)([a-zA-Z0-9_-]{11})', url)
    vid = match.group(1) if match else url
    fetch(vid)
else:
    print(json.dumps({"error": "No URL provided"}))
